modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors = "Satou"
description = "${mod_description}"
displayURL = "${mod_url}"
credits = ""

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "[7,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "gtmthings"
mandatory = true
versionRange = "1.5.4"
ordering = "BEFORE"
side = "BOTH"